# Generated by Django 5.2.6 on 2025-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
