# Generated by Django 5.2.6 on 2025-09-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0002_user_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_description',
        ),
    ]
