# Generated by Django 5.2.6 on 2025-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0007_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('profession', models.CharField(default='Student', max_length=50)),
                ('password', models.CharField(default='12345678', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(default='Vizianagaram', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Vizianagaram', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
