# Generated by Django 5.2.6 on 2025-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0008_volunteer_user_address_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='No image', upload_to='images'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(default='No Image', upload_to='images'),
        ),
    ]
