# Generated by Django 5.2.6 on 2025-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0009_user_photo_volunteer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
