# Generated by Django 5.2.6 on 2025-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/profile.jpg', upload_to='images'),
        ),
    ]
