# Generated by Django 5.2.6 on 2025-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0013_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('feedback', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=30)),
            ],
        ),
    ]
