# Generated by Django 5.2.6 on 2025-10-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345678', max_length=128),
        ),
    ]
