# Generated by Django 5.2.6 on 2025-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='event_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
