# Generated by Django 5.2.6 on 2025-10-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0017_posts_event_date_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_phones', to='Community_Hub.user'),
        ),
    ]
