# Generated by Django 5.2.6 on 2025-10-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0018_alter_posts_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
