# Generated by Django 5.2.6 on 2025-10-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0020_volunteermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Community_Hub.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_posts', to='Community_Hub.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to='Community_Hub.user'),
        ),
        migrations.AlterField(
            model_name='volunteermessage',
            name='status',
            field=models.CharField(default='sent', max_length=30),
        ),
    ]
