# Generated by Django 5.2.6 on 2025-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0022_alter_volunteer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phone_number',
            new_name='author_phone_number',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
