# Generated by Django 5.2.6 on 2025-10-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community_Hub', '0023_rename_phone_number_post_author_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='Community_Hub.post')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_verifications', to='Community_Hub.volunteer')),
            ],
            options={
                'unique_together': {('post', 'volunteer')},
            },
        ),
    ]
